{% set name = "codar2netcdf" %}
{% set version = "0.0.2" %}
{% set md5 = "30163273ed1d8e8578249731e6d99e73" %}
{% set build = 0 %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    md5: {{ md5 }}

build:
    number: {{ build }}
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - pandas
        - netcdf4
        - pytz
        - python-dateutil

test:
    imports:
        - codar2netcdf
        - codar2netcdf.tests
    requires:
        - pytest

about:
    home: https://github.com/axiom-data-science/codar2netcdf
    license: MIT License
    summary: 'A utility to convert CODAR total ASCII files into CF NetCDF files.'

extra:
    recipe-maintainers:
        - ocefpaf
        - kwilcox
