travis:
  secure:
    BINSTAR_TOKEN: dHYNUvq5eshGOMttFee4dNQn1jS1ry6ddoUJ2Bq9vxKbFjYD+vK5OOjNevxyZlBIXIy+y5QMoV30rHtZ79q8Bf4lUVJ8GC/IxcidVD2+I3aHkH+4WqKpvq+qvWIhNWrnLazxF57g3E6y4GUR59ae012/OUTpu8jPvSBqSzSnW049mXV3HAnFGRuxONrnyChO5rbu+D58jcLJ99cLVKM7kzqOsfVoG4inFvdV6I1vMSdph870ols1lzhJviaFQ3hRypqCxcBe2rfWiJ/QpnDrp6yxs3DLcGpZsHoInzl3cSoNk1CsNv55E3NJcHg021PxwaGoSluokebjm6K2cfeKBUCnetDBoSPZBaIaZfKvF3twSNs1i08cOYqZHstKTBQxmYQF9H19q4RiBSyuMb97exhLC3FhQm7HR3bZaJLO0pHhTwazMgmaYiroKRgtMG4oAZ92GrqC4WsyeBPDKCDw9ZVG1x4SxEYLzeDFfeuyL6wx1O+hsUBCxCSY2LZNZYh7uaPZ9r8psujBqBgjcgvTnmBWrx/jiuXkXY8JTBFiJL/o1RXdaj4N/MPbD5Qyj1Rm+1MfL7jZWSJW7q4SIcHYHjAWtiOd1F0WmWCtvzj/muvuDb0sWBBP2xjMh5jT6+ZM6bfoBUw+tUFiZ3al4jNUyFm6+hykMq9rUsPLw4mKnsM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
